Map<String, List<String>> countryStates = {
  "Select State/Region": ["Select State/Region"],
  "Algeria": [
    "Select State/Region",
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Alger",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arreridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane"
  ],
  "Angola": [
    "Select State/Region",
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cunene",
    "Huambo",
    "Huíla",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire"
  ],
  "Benin": [
    "Select State/Region",
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Donga",
    "Kouffo",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou"
  ],
  "Botswana": [
    "Select State/Region",
    "Central",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "North East",
    "North West",
    "South East",
    "Southern"
  ],
  "Burkina Faso": [
    "Select State/Region",
    "Balé",
    "Bam",
    "Banwa",
    "Bazèga",
    "Bougouriba",
    "Boulgou",
    "Boulkiemdé",
    "Comoe",
    "Ganzourgou",
    "Gnagna",
    "Gourma",
    "Houet",
    "Ioba",
    "Kadiogo",
    "Kénédougou",
    "Komondjari",
    "Kompienga",
    "Kossi",
    "Koulpélogo",
    "Kouritenga",
    "Kourwéogo",
    "Léraba",
    "Loroum",
    "Mouhoun",
    "Nahouri",
    "Namentenga",
    "Nayala",
    "Noumbiel",
    "Oubritenga",
    "Oudalan",
    "Passoré",
    "Poni",
    "Sanguié",
    "Sanmatenga",
    "Séno",
    "Sissili",
    "Soum",
    "Sourou",
    "Tapoa",
    "Tuy",
    "Yagha",
    "Yatenga",
    "Ziro",
    "Zondoma",
    "Zoundwéogo"
  ],
  "Burundi": [
    "Select State/Region",
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rumonge",
    "Rutana",
    "Ruyigi"
  ],
  "Cameroon": [
    "Select State/Region",
    "Adamaoua",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "Northwest",
    "South",
    "Southwest",
    "West"
  ],
  "Central African Republic": [
    "Select State/Region",
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haute-Kotto",
    "Haut-Mbomou",
    "Kémo",
    "Lobaye",
    "Mambéré-Kadéï",
    "Mbomou",
    "Nana-Grébizi",
    "Nana-Mambéré",
    "Ombella-M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Vakaga"
  ],
  "Chad": [
    "Select State/Region",
    "Bahr el Gazel",
    "Batha",
    "Borkou",
    "Chari-Baguirmi",
    "Ennedi",
    "Guéra",
    "Hadjer-Lamis",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kébbi Est",
    "Mayo-Kébbi Ouest",
    "Moyen-Chari",
    "N'Djamena",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Wadi Fira"
  ],
  "Comoros": ["Select State/Region", "Anjouan", "Grande Comore", "Mohéli"],
  "Congo (Brazzaville)": [
    "Select State/Region",
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lékoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Pool",
    "Sangha"
  ],
  "Congo (Kinshasa)": [
    "Select State/Region",
    "Bas-Uele",
    "Haut-Uele",
    "Haut-Lomami",
    "Haut-Katanga",
    "Haut-Lomami",
    "Haut-Uele",
    "Ituri",
    "Kasaï",
    "Kasaï-Central",
    "Kasaï-Oriental",
    "Kasai-Occidental",
    "Kinshasa",
    "Kwilu",
    "Kwango",
    "Lomami",
    "Mongala",
    "Nord-Ubangi",
    "Nord-Kivu",
    "Maniema",
    "Mongala",
    "Nord-Ubangi",
    "Nord-Kivu",
    "Orientale",
    "Sankuru",
    "Sud-Kivu",
    "Sud-Ubangi",
    "Tanganyika",
    "Tshopo",
    "Tshuapa"
  ],
  "Cote d'Ivoire": [
    "Select State/Region",
    "Agnéby-Tiassa",
    "Bafing",
    "Bas-Sassandra",
    "Denguélé",
    "Dix-Huit Montagnes",
    "Fromager",
    "Haut-Sassandra",
    "Lacs",
    "Lagunes",
    "Marahoué",
    "Moyen-Cavally",
    "Moyen-Comoé",
    "N'zi-Comoé",
    "Savanes",
    "Sud-Bandama",
    "Sud-Comoé",
    "Vallée du Bandama",
    "Woroba",
    "Zanzan"
  ],
  "Djibouti": [
    "Select State/Region",
    "Ali Sabieh",
    "Arta",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjourah"
  ],
  "Egypt": [
    "Select State/Region",
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr el-Sheikh",
    "Luxor",
    "Matruh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez"
  ],
  "Equatorial Guinea": [
    "Select State/Region",
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kié-Ntem",
    "Litoral",
    "Wele-Nzas"
  ],
  "Eritrea": [
    "Select State/Region",
    "Anseba",
    "Central",
    "Gash-Barka",
    "Northern Red Sea",
    "Southern",
    "Southern Red Sea"
  ],
  "Eswatini": [
    "Select State/Region",
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "Ethiopia": [
    "Select State/Region",
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Dire Dawa",
    "Gambela",
    "Harari",
    "Oromia",
    "Sidama",
    "Somali",
    "Southern Nations, Nationalities, and Peoples' Region (SNNPR)",
    "Tigray"
  ],
  "Gabon": [
    "Select State/Region",
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem"
  ],
  "Gambia": [
    "Select State/Region",
    "Banjul",
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "West Coast"
  ],
  "Ghana": [
    "Select State/Region",
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono East",
    "Central",
    "Eastern",
    "Greater Accra",
    "North East",
    "Northern",
    "Oti",
    "Savannah",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Western North"
  ],
  "Guinea": [
    "Select State/Region",
    "Boké",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Nzérékoré"
  ],
  "Guinea-Bissau": [
    "Select State/Region",
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama-Bijagos",
    "Cacheu",
    "Gabú",
    "Oio",
    "Quinara",
    "Tombali"
  ],
  "Kenya": [
    "Select State/Region",
    "Nairobi",
    "Mombasa",
    "Kwale",
    "Kilifi",
    "Tana River",
    "Lamu",
    "Taita-Taveta",
    "Garissa",
    "Wajir",
    "Mandera",
    "Marsabit",
    "Isiolo",
    "Meru",
    "Tharaka-Nithi",
    "Embu",
    "Kitui",
    "Machakos",
    "Makueni",
    "Nyandarua",
    "Nyeri",
    "Kirinyaga",
    "Murang'a",
    "Kiambu",
    "Turkana",
    "West Pokot",
    "Samburu",
    "Trans-Nzoia",
    "Uasin Gishu",
    "Elgeyo-Marakwet",
    "Nandi",
    "Baringo",
    "Laikipia",
    "Nakuru",
    "Narok",
    "Kajiado",
    "Kericho",
    "Bomet",
    "Kakamega",
    "Vihiga",
    "Bungoma",
    "Busia",
    "Siaya",
    "Kisumu",
    "Homa Bay",
    "Migori",
    "Kisii",
    "Nyamira"
  ],
  "Lesotho": [
    "Select State/Region",
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka"
  ],
  "Liberia": [
    "Select State/Region",
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Cess",
    "River Gee",
    "Sinoe"
  ],
  "Libya": [
    "Select State/Region",
    "Al Wahat",
    "Benghazi",
    "Derna",
    "Ghat",
    "Jabal al Akhdar",
    "Jabal al Gharbi",
    "Jafara",
    "Jufra",
    "Kufra",
    "Marj",
    "Misrata",
    "Murqub",
    "Nalut",
    "Nuqat al Khams",
    "Sabha",
    "Sirte",
    "Tripoli",
    "Wadi al Hayaa",
    "Wadi al Shatii",
    "Zawiya"
  ],
  "Madagascar": [
    "Select State/Region",
    "Alaotra-Mangoro",
    "Amoron'i Mania",
    "Analamanga",
    "Analanjirofo",
    "Androy",
    "Anosy",
    "Atsimo-Andrefana",
    "Atsimo-Atsinanana",
    "Atsinanana",
    "Betsiboka",
    "Boeny",
    "Bongolava",
    "Diana",
    "Haute Matsiatra",
    "Ihorombe",
    "Itasy",
    "Melaky",
    "Menabe",
    "Sava",
    "Sofia",
    "Vakinankaratra",
    "Vatovavy-Fitovinany"
  ],
  "Malawi": [
    "Select State/Region",
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulu",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongwe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Neno",
    "Nkhata Bay",
    "Nkhotakota",
    "Nsanje",
    "Ntcheu",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Thyolo",
    "Zomba"
  ],
  "Mali": [
    "Select State/Region",
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Ménaka",
    "Mopti",
    "Ségou",
    "Sikasso",
    "Taoudénit",
    "Tombouctou"
  ],
  "Mauritania": [
    "Select State/Region",
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott",
    "Tagant",
    "Tiris Zemmour",
    "Trarza"
  ],
  "Mauritius": [
    "Select State/Region",
    "Agalega Islands",
    "Beau Bassin-Rose Hill",
    "Cargados Carajos Shoals",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Quatre Bornes",
    "Rivière du Rempart",
    "Rodrigues",
    "Savanne",
    "Vacoas-Phoenix"
  ],
  "Morocco": [
    "Select State/Region",
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Dakhla-Oued Ed-Dahab",
    "Drâa-Tafilalet",
    "Fès-Meknès",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Marrakech-Safi",
    "Oriental",
    "Rabat-Salé-Kénitra",
    "Souss-Massa",
    "Tanger-Tétouan-Al Hoceima"
  ],
  "Mozambique": [
    "Select State/Region",
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia"
  ],
  "Namibia": [
    "Select State/Region",
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango East",
    "Kavango West",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
    "Zambezi"
  ],
  "Niger": [
    "Select State/Region",
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillabéri",
    "Zinder"
  ],
  "Nigeria": [
    "Select State/Region",
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
    "Federal Capital Territory (FCT)"
  ],
  "Rwanda": [
    "Select State/Region",
    "Eastern",
    "Kigali",
    "Northern",
    "Southern",
    "Western"
  ],
  "Sao Tome and Principe": ["Select State/Region", "Príncipe", "São Tomé"],
  "Senegal": [
    "Select State/Region",
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Ziguinchor"
  ],
  "Seychelles": [
    "Select State/Region",
    "La Digue and Inner Islands",
    "Outer Islands",
    "Praslin"
  ],
  "Sierra Leone": [
    "Select State/Region",
    "Eastern",
    "Northern",
    "Southern",
    "Western Area"
  ],
  "Somalia": [
    "Select State/Region",
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiiraan",
    "Jubbada Dhexe",
    "Jubbada Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabeellaha Dhexe",
    "Shabeellaha Hoose",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed"
  ],
  "South Africa": [
    "Select State/Region",
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape"
  ],
  "South Sudan": [
    "Select State/Region",
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria"
  ],
  "Sudan": [
    "Select State/Region",
    "Al Qadarif",
    "Blue Nile",
    "Central Darfur",
    "East Darfur",
    "Kassala",
    "Khartoum",
    "North Darfur",
    "North Kordofan",
    "Northern",
    "Red Sea",
    "River Nile",
    "Sennar",
    "South Darfur",
    "South Kordofan",
    "West Darfur",
    "White Nile"
  ],
  "Tanzania": [
    "Select State/Region",
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Pemba North",
    "Pemba South",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Simiyu",
    "Singida",
    "Tabora",
    "Tanga",
    "Zanzibar Central/South",
    "Zanzibar North",
    "Zanzibar Urban/West"
  ],
  "Togo": [
    "Select State/Region",
    "Centrale",
    "Kara",
    "Maritime",
    "Plateaux",
    "Savanes"
  ],
  "Tunisia": [
    "Select State/Region",
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kébili",
    "La Manouba",
    "Le Kef",
    "Mahdia",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
  ],
  "Uganda": [
    "Select State/Region",
    "Central",
    "Eastern",
    "Northern",
    "Western"
  ],
  "Zambia": [
    "Select State/Region",
    "Central",
    "Copperbelt",
    "Eastern",
    "Luapula",
    "Lusaka",
    "Muchinga",
    "North-Western",
    "Northern",
    "Southern",
    "Western"
  ],
  "Zimbabwe": [
    "Select State/Region",
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands"
  ]
};
